### ISSUE TITLE
Pull color variables from a custom drupal theme

### ISSUE THREAD

**Issue by janette** [GetDKAN/data-catalog-frontend#43]
1. Hook into Drupal core use of the color module: https://medium.codekoalas.com/integrating-the-color-module-into-your-drupal-8-theme-5e9b32db690d
2. Generate a stylesheet from that config if it exists, otherwise use the default color scheme.

**Comment by dgading** [comment]
Recreated on React App here: https://github.com/GetDKAN/data-catalog-react/issues/21
